version: '3'

services:
  api:
    build:
      context: .
      dockerfile: src/CacheProxyService/Dockerfile
    depends_on:
      - cache
    ports:
      - '80:80'
    environment:
      - 'DADATA_TOKEN=${DADATA_TOKEN}'
      - 'REDIS_URL=cache:6379'
    
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
